int backend_getascent();
void backend_getmetrics(char c, int *minx, int *maxx, int *miny, int *maxy, int *advance);
void backend_glyph(char c, unsigned int x, unsigned int y, unsigned int w, unsigned int h, unsigned int color);
void backend_rect(int x, int y, int w, int h);
void backend_pollevent(void (*quit)(), void (*keydown)(unsigned int key));
void backend_waitevent(void (*quit)(), void (*keydown)(unsigned int key));
void backend_render(void (*render)());
void backend_init();
void backend_destroy();
void backend_loadbackground(char *name);
void backend_loadfont(char *name);
void backend_unloadbackground();
void backend_unloadfont();
