int backend_font_getascent(void);
void backend_font_getmetrics(char c, int *minx, int *maxx, int *miny, int *maxy, int *advance);
void backend_paint_glyph(char c, unsigned int x, unsigned int y, unsigned int w, unsigned int h, unsigned int color);
void backend_paint_icon(unsigned int x, unsigned int y, unsigned int w, unsigned int h, unsigned int type);
void backend_paint_slider(int x, int y, int w, int h, int ws, unsigned int ticks);
void backend_paint_selection(int x, int y, int w, int h);
void backend_pollevent(void (*quit)(void), void (*button)(unsigned int key));
void backend_waitevent(void (*quit)(void), void (*button)(unsigned int key));
void backend_render(struct view *view, unsigned int ticks);
unsigned int backend_ticks(void);
void backend_delay(unsigned int ms);
void backend_play(char *name);
void backend_tilebackground(char *name);
void backend_loadimage(char *name, char *path);
void backend_loadsample(char *name, char *path);
void backend_loadtextfont(char *name);
void backend_loadsmalliconfont(char *name);
void backend_loadlargeiconfont(char *name);
void backend_unloadbackground(void);
void backend_unloadimage(char *name);
void backend_unloadsample(char *name);
void backend_unloadfonts(void);
void backend_init(void);
void backend_destroy(void);
