int backend_getascent(void);
void backend_getmetrics(char c, int *minx, int *maxx, int *miny, int *maxy, int *advance);
void backend_glyph(char c, unsigned int x, unsigned int y, unsigned int w, unsigned int h, unsigned int color);
void backend_rect(int x, int y, int w, int h);
void backend_pollevent(void (*quit)(void), void (*button)(unsigned int key));
void backend_waitevent(void (*quit)(void), void (*button)(unsigned int key));
void backend_render(unsigned int ticks, void (*place)(unsigned int w, unsigned int h), void (*render)(unsigned int ticks));
unsigned int backend_ticks(void);
void backend_delay(unsigned int ms);
void backend_init(void);
void backend_destroy(void);
void backend_loadbackground(char *name);
void backend_loadfont(char *name);
void backend_loadaudio(void);
void backend_unloadbackground(void);
void backend_unloadfont(void);
void backend_unloadaudio(void);
void backend_play(char *name);
