#define SCREEN_WIDTH                    320
#define SCREEN_HEIGHT                   240
#define SCREEN_BPP                      32
#define TIMELIMIT                       (1000 / 60)
#define MAXWIDGETS                      2000
#define MAXSESSIONS                     32
#define MAXDOWNLOADS                    8
#define REPEAT_FIRST                    32
#define REPEAT_SECOND                   4
#define BUTTON_LEFT                     1
#define BUTTON_RIGHT                    2
#define BUTTON_UP                       3
#define BUTTON_DOWN                     4
#define BUTTON_A                        5
#define BUTTON_B                        6
#define BUTTON_X                        7
#define BUTTON_Y                        8
#define BUTTON_L                        9
#define BUTTON_R                        10
#define BUTTON_SELECT                   11
#define BUTTON_START                    12
#define BUTTON_LOCKDOWN                 13
#define BUTTON_LOCKUP                   14
#define VIEW_LOADTYPE_INIT              1
#define VIEW_LOADTYPE_RESTORE           2
#define TEXT_TYPE_NORMAL                1
#define TEXT_TYPE_TITLE                 2
#define TEXT_TYPE_SELECT                3
#define TEXT_TYPE_DISABLE               4
#define TEXT_ALIGN_LEFT                 0
#define TEXT_ALIGN_RIGHT                1
#define TEXT_ALIGN_CENTER               2
#define TEXT_ROWHEIGHT                  20
#define TOGGLE_OFF                      0
#define TOGGLE_ON                       1
#define TOGGLE_OFF_DISABLED             2
#define TOGGLE_ON_DISABLED              3
#define ICON_AUDIO                      0xEEA8
#define ICON_CLOCK                      0xF022
#define ICON_NETWORK                    0xF02B
#define ICON_SYSTEM                     0xEA4D
