#define SCREEN_WIDTH                    320
#define SCREEN_HEIGHT                   240
#define SCREEN_BPP                      32
#define KEY_LEFT                        1
#define KEY_RIGHT                       2
#define KEY_UP                          3
#define KEY_DOWN                        4
#define KEY_A                           5
#define KEY_B                           6
#define KEY_X                           7
#define KEY_Y                           8
#define KEY_L                           9
#define KEY_R                           10
#define KEY_SELECT                      11
#define KEY_START                       12
#define KEY_LOCKDOWN                    13
#define KEY_LOCKUP                      14
#define TEXT_COLOR_NORMAL               0xFFA0C0C0
#define TEXT_COLOR_TITLE                0xFFE0E0E0
#define TEXT_COLOR_SELECT               0xFFE06020
#define TEXT_COLOR_DISABLE              0xFF406060
#define TEXT_ALIGN_LEFT                 0
#define TEXT_ALIGN_RIGHT                1
#define TEXT_ALIGN_CENTER               2
#define TEXT_ROWHEIGHT                  20
