#define SCREEN_WIDTH                    320
#define SCREEN_HEIGHT                   240
#define SCREEN_BPP                      32
#define TIMELIMIT                       (1000 / 60)
#define KEY_LEFT                        1
#define KEY_RIGHT                       2
#define KEY_UP                          3
#define KEY_DOWN                        4
#define KEY_A                           5
#define KEY_B                           6
#define KEY_X                           7
#define KEY_Y                           8
#define KEY_L                           9
#define KEY_R                           10
#define KEY_SELECT                      11
#define KEY_START                       12
#define KEY_LOCKDOWN                    13
#define KEY_LOCKUP                      14
#define TEXT_TYPE_NORMAL                1
#define TEXT_TYPE_TITLE                 2
#define TEXT_TYPE_SELECT                3
#define TEXT_TYPE_DISABLE               4
#define TEXT_ALIGN_LEFT                 0
#define TEXT_ALIGN_RIGHT                1
#define TEXT_ALIGN_CENTER               2
#define TEXT_ROWHEIGHT                  20
#define TOGGLE_OFF                      0
#define TOGGLE_ON                       1
#define TOGGLE_OFF_DISABLED             2
#define TOGGLE_ON_DISABLED              3
#define ICON_AUDIO                      0xEEA8
#define ICON_NETWORK                    0xF02B
#define ICON_SYSTEM                     0xEA4D
